### ISSUE TITLE
error in WinMain

### ISSUE THREAD

**Issue by bvanevery** [gawag/Urho-Sample-Platformer#11]
In Visual Studio building against Urho3D 1.4, I get the following error:

```
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\main.cpp(133): error C2146: syntax error: missing ';' before identifier 'WinMain'
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\main.cpp(133): error C2065: 'HINSTANCE': undeclared identifier
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\main.cpp(133): error C2146: syntax error: missing ')' before identifier 'hInstance'
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\main.cpp(133): error C2143: syntax error: missing ';' before '{'
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\main.cpp(133): error C2447: '{': missing function header (old-style formal list?)
1>  Generating Code...
```

This smells like an include file declared in the wrong order somehow.

**Comment by damu** [comment]
Could be fixed now. I expanded the macro to the normal and general int main version.

**Comment by bvanevery** [comment]
Different error now, isn't fixed.  Not sure what's going on with the intermediate directory thing.

```
1>------ Build started: Project: Urho-Sample-Platformer, Configuration: Release x64 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (Urho-Sample-Platformer.dir\Release\) contains files shared from another project (Urho-Sample-Platformer.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>     Creating library C:/Users/BVANEVRY/devel/build/Urho-Sample-Platformer-1.4/Release/Urho-Sample-Platformer.lib and object C:/Users/BVANEVRY/devel/build/Urho-Sample-Platformer-1.4/Release/Urho-Sample-Platformer.exp
1>MSVCRT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
1>C:\Users\BVANEVRY\devel\build\Urho-Sample-Platformer-1.4\bin\Urho-Sample-Platformer.exe : fatal error LNK1120: 1 unresolved externals
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========
```

**Comment by damu** [comment]
" warning MSB8028: The intermediate directory (Urho-Sample-Platformer.dir\Release) contains files shared from another project (Urho-Sample-Platformer.vcxproj).  This can lead to incorrect clean and rebuild behavior."
Sound like CMake or Visual Studio fuckup. Try deleting the build and project files and recreate them. Maybe recreating the project/build files clashed with the already used ones. Oh its just a warning anyway. Maybe that can be ignored.

The second about missing WinMain: http://stackoverflow.com/questions/6626397/error-lnk2019-unresolved-external-symbol-winmain16-referenced-in-function
CMake seems to set the project type to Win32 or something and the compiler expects a WinMain function instead of a normal int main. I pushed another change that should fix this error.

**Comment by bvanevery** [comment]
I've now pulled and built clean.  The intermediate directory error is gone, probably just some stale CMake thing.  The WinMain issue remains unchanged:

```
1>------ Build started: Project: Urho-Sample-Platformer, Configuration: Release x64 ------
1>     Creating library C:/Users/BVANEVRY/devel/build/Urho-Sample-Platformer-1.4/Release/Urho-Sample-Platformer.lib and object C:/Users/BVANEVRY/devel/build/Urho-Sample-Platformer-1.4/Release/Urho-Sample-Platformer.exp
1>MSVCRT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
1>C:\Users\BVANEVRY\devel\build\Urho-Sample-Platformer-1.4\bin\Urho-Sample-Platformer.exe : fatal error LNK1120: 1 unresolved externals
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========
```

The #ifdef logic seems to be wrong somehow.  When I click "go to definition" in VS, I get the very last definition, which just defines main().  I do not have URHO_WIN32_CONSOLE defined, nor did I when building Urho3D.  The default is not to define it.  The brief text explanation says it's for providing main() instead of WinMain().  Hmm, maybe it's just the VS editor not knowing what the defines are, and dropping to the final #else case.

Why are you relying on WIN32 to determine if WinMain is needed?  I'm building on 64-bit Windows.  Hmm, now I'm remembering that it's an archaic CMake define for "we're on Windows".  Comes from before the 64-bit era.  It is actually defined in my CMake configuration, so I'll stare at this more.

Clean built again.   Made really really sure it's clean, deleted build directory and all.  Problem isn't going away.

CMakeLists.txt contains a function "setup_main_executable ()" which is defined in Urho-Sample-Platformer\CMake\Modules\Urho3D-CMake-common.cmake.  The definition is pretty complicated.  I have no idea what it does.  Maybe something is going wrong in there.  I can't honestly see why it would be a good practice to use some thing so obfuscated to do anything in CMake.  I'm guessing you lifted this from the Urho3D codebase?  Seems like a bad idea.

I activated "Preprocess to a File", aka /P.  main.i shows:

```
int RunApplication()
{
    Urho3D::SharedPtr<Urho3D::Context> context(new Urho3D::Context());
    Urho3D::SharedPtr<USP> application(new USP(context));
    return application->Run();
}
int main(int argc, char** argv) { Urho3D::ParseArguments(argc, argv); return RunApplication(); };
```

I don't understand why it's not getting the defines.  They seem to be defined; guess what "seems" doesn't matter.  Ok, it has to be that WIN32 is not actually defined as a preprocessor symbol.  Could it be as simple as, WIN32 is a CMake only scripting symbol (also misnamed for that matter), not a preprocessor definition, so it's being used incorrectly?  The actual Windows platform define for VS 2015 is _WIN32.  https://msdn.microsoft.com/en-us/library/b0084kay.aspx  Maybe this is an upstream bug in Urho3D-1.4\include\Urho3D\Core\main.h.

**Comment by bvanevery** [comment]
After discussion in the Urho3D support forum, I filed an upstream bug regarding WIN32 vs. _WIN32.  https://github.com/urho3d/Urho3D/issues/1036  Unfortunately Urho3D 1.5 shipped using WIN32, so if you want to write against that, you'll need to come up with a workaround.

I'm a little perplexed as to CMake's role in all of this.  When I look at my Urho3D 1.4 build in Visual Studio, it's getting a /D "WIN32" on its command lines.  But for USP it is not.

**Comment by bvanevery** [comment]
The Urho3D guys changed everything to _WIN32 which is The Right Thing To Do [TM], but it wasn't actually the source of the problem.  Best I can tell from looking at other CMake projects, CMake _initializes_ CMAKE_CXX_FLAGS and other similar variables.  Projects that don't do any special configuration at all, such as https://github.com/dennis-kk/knet , get " /DWIN32 /D_WINDOWS /W3 /GR /EHsc" by default.  You should not overwrite CMAKE_CXX_FLAGS unless you really intend to get rid of those defaults.  In your top level CMakeLists.txt you have:

```
set (CMAKE_CXX_FLAGS "-std=c++11")
```

which kills the defaults.  Rather than modify this variable directly, it is probably better form to use the add_compile_options command.  

BTW "-std=c++11" is an unknown option for VS 2015 anyways.  It gives a warning during the build.  Some of the other flags like /EHsc are also needed for the build, to enable C++ exception handling unwind semantics.  These issues could be causing other problems, depending on what you were trying to do with C++11.

**Comment by bvanevery** [comment]
The problem of overwriting CMAKE_CXX_FLAGS still exists.  It won't affect Urho3D 1.5+ development versions, because I convinced them upstream to change to the standard _WIN32 compiler macro instead of WIN32.  However the problem will probably still manifest in Urho3D 1.5, as that change came after 1.5 was shipped.

**Comment by damu** [comment]
Oh I didn't know I was overwriting stuff with setting CMAKE_CXX_FLAGS.
I just pushed a commit that replaced the "set" with a "add_compile_options". It's still working for me with GCC. I just searched and Visual Studio should have enabled C++11 by default so it should work now (besides that one warning).
Does it work?

**Comment by bvanevery** [comment]
Verified that " /DWIN32 /D_WINDOWS /W3 /GR /EHsc" are now present.  Bug crushed!
